### ISSUE TITLE
Need a way to register Feature during JAX-RS runtime

### ISSUE THREAD

**Issue by dkoyro** [nhl/bootique-jersey#11]
There is a case when our application REST endpoint consumes a ```MediaType.MULTIPART_FORM_DATA``` type parameter:
```javascript
import org.glassfish.jersey.media.multipart.FormDataParam;
...
@Path("mypath")
public class MyResource {

@POST
@Path("upload")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.MULTIPART_FORM_DATA)
public Response uploadMultiPart(@FormDataParam("upload") InputStream inputStream) {...}
...
}
```
so ```org.glassfish.jersey.media.multipart.MultiPartFeature``` feature should be activated during Jersey runtime. 
This feature injects necessary message body readers, writers to our Jersey application. 

Currently there is the only way to register a Feature is to contribute it when our application Module is being configured by using JerseyModule.contributeFeatures() API:
```javascript
import org.glassfish.jersey.media.multipart.MultiPartFeature;
...
@Overrride
public void configure(Binder binder) {
...
JerseyModule.contributeFeatures(binder).addBinding().to(MultiPartFeature.class);
...}
```
But it's seems that it's too late and the application fails with the following error:
> org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
> [FATAL] No injection source found for a parameter of type ...
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:553) ~[jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:182) ~[jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:348) ~[jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:345) ~[jersey-server-2.21.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:345) ~[jersey-server-2.21.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:390) ~[jersey-container-servlet-core-2.21.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:170) ~[jersey-container-servlet-core-2.21.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:362) ~[jersey-container-servlet-core-2.21.jar:na]
	at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-3.0.0.v201112011016.jar:na]
...
	at org.eclipse.jetty.server.Server.doStart(Server.java:372) [jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.3.6.v20151106.jar:9.3.6.v20151106]
	at com.nhl.bootique.jetty.command.ServerCommand.run(ServerCommand.java:37) [bootique-jetty-0.12.jar:0.12]
	at com.nhl.bootique.run.DefaultRunner.run(DefaultRunner.java:22) [bootique-0.12.jar:0.12]

**Comment by andrus** [comment]
Wrote a [unit test](https://github.com/nhl/bootique-jersey/blob/master/src/test/java/com/nhl/bootique/jersey/MultiPartFeatureIT.java) ... Seems to be working in the test environment.
